app = 'ani-postgres'
primary_region = 'hkg'

[build]
  image = "postgres:15"

[mounts]
  source = 'pg_data'
  destination = '/var/lib/postgresql/data'

[env]
  POSTGRES_USER = "postgres"
  POSTGRES_DB = "newsletter"

[[services]]
  protocol = "tcp"
  internal_port = 5432

  [[services.ports]]
    port = 5432

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"
    restart_limit = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
