# fly.toml for ani-postgres
app = "ani-postgres"
primary_region = "hkg"

[build]
  image = "postgres:15"

# 不挂载卷
#[mounts]
#  source = "pg_data"
#  destination = "/var/lib/postgresql/data/db"

[env]
  PGDATA = "/var/lib/postgresql/data"
  POSTGRES_USER = "postgres"
  POSTGRES_DB = "newsletter"
  TZ = "Asia/Shanghai"  
  # 密码使用 secrets 设置，不在 toml 中写
  # POSTGRES_PASSWORD = "your-strong-password"

[[services]]
  protocol = "tcp"
  internal_port = 5432

  [[services.ports]]
    port = 5432

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"
    restart_limit = 0

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
