# fly.toml app configuration file generated for ani-postgres on 2025-08-28T13:27:31+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ani-postgres'
primary_region = 'hkg'

[build]

[[mounts]]
  source = 'data'
  destination = '/var/lib/postgresql/data'

[http_service]
  internal_port = 5432
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
